### ISSUE TITLE
Error Messge from perf-pmu.py 

### ISSUE THREAD

**Issue by billstore** [cloudswenable/ptap#11]
I execute the cmmand perf-pmu.py, get the following message.  In fact . the directory 'outpath'  has crated after executing perf-hotspots.py  

> > python perf-pmu.py -o out  path/prefix -p 6189 -r 1 -i 2
> > /bin/sh: perf: command not found
> > Traceback (most recent call last):
> >   File "perf-pmu.py", line 147, in <module>
> >     parse(fname)
> >   File "perf-pmu.py", line 99, in parse
> >     parseFile(fname)
> >   File "perf-pmu.py", line 24, in parseFile
> >     rawfile = open(fname, 'r')
> > IOError: [Errno 2] No such file or directory: 'outpath/prefix-20150605043639'

**Comment by cloudswenable** [comment]
which branch?  experiment?

**Comment by you-n-g** [comment]
@billstore 

first,  make sure you are on branch experiment.

Second
I created a folder named `outpath`  and  tested with command `python perf-pmu.py -o outpath/prefix -p 26524 -r 1 -i 2`  just now  Nothing wrong happend.

I noticed you use  `python perf-pmu.py -o out path/prefix -p 6189 -r 1 -i 2`.  It seems there is a blank between  `out` and `path/prefix`. Is that a typo?

**Comment by billstore** [comment]
是从你邮件里的地址下载的代码:https://github.com/cloudswenable/ptap/tree/experiment
这个空格是编辑时输入的,在控制台执行命令时没有空格

**Comment by billstore** [comment]
已解决。
需要在环境变量PATH中增加<PTAP home>/tools 以便可以找到perf。
